FROM python:3.12-slim
ENV LOG_LEVEL=debug
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY logging.yaml ./logging.yaml
COPY .env ./.env
COPY pyproject.toml ./pyproject.toml
COPY src/ ./src
RUN pip install .
EXPOSE 8000

ENTRYPOINT ["sh", "-c", "uvicorn bot_connectors.main:app --host 0.0.0.0 --port 8000 --log-level $LOG_LEVEL --log-config logging.yaml"]
