version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [ console ]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [ console ]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [ console ]
    propagate: no

  bot_connectors:
    level: DEBUG
    handlers: [ console ]
    propagate: no

root:
  level: DEBUG
  handlers: [ console ]
