FROM oven/bun:1-alpine AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build --mode development
ENV SERVE_API=local
ENV PORT=3000
EXPOSE 3000
CMD ["sh", "-c", "bun run serve:$SERVE_API --port $PORT"]
