FROM node:22.17.0-alpine AS builder

WORKDIR /app

COPY package.json .yarnrc.yml yarn.lock .pnp.cjs .pnp.loader.mjs ./
RUN corepack enable
RUN yarn set version 4.9.2
COPY . .
RUN yarn install --immutable
RUN yarn build
ENV SERVE_API=local
ENV PORT=3000
EXPOSE 3000
CMD ["sh", "-c", "yarn serve:$SERVE_API --port $PORT"]