FROM node:22.17.0-alpine as builder

WORKDIR /app

COPY package.json .yarnrc.yml yarn.lock .pnp.cjs .pnp.loader.mjs ./
RUN corepack enable
RUN yarn set version 4.9.2
COPY . .
RUN yarn install --immutable
RUN yarn build

FROM  nginx:stable-alpine as production
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
